<a href="https://colab.research.google.com/github/Prochorus-rai/FoundationAI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Header H1

In [1]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [4]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [9]:
a=([1,2,3,4,5,6,7,10])


In [10]:
a[2]=10

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
a

[1, 2, 10, 4, 5, 6, 7, 10]

In [14]:
np.linspace(0,100,11)#create arrays eith evenly space numbers within a spec

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multidimensational array

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.zeros(((3,6)))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
a

[1, 2, 10, 4, 5, 6, 7, 10]

In [24]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
n[2] = [1,1,1]

In [26]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

# Randomly generated arrays
Numpy can create arrays filled with random numbers. to ensure reproduction, you can set a seed using np random.seed():
Every time you run this code with  p random

In [54]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [46]:
np.random.rand(4,3)

array([[0.48358553, 0.36217621, 0.70768662],
       [0.74674622, 0.69109292, 0.68918041],
       [0.37360012, 0.6681348 , 0.33984866],
       [0.57279387, 0.32580716, 0.44514505]])

In [ ]:
np.random.seed(2)

Element wise you can perform operationson entire ararys

In [56]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [57]:
b = (10 +(a*2))

In [58]:
b

array([10, 12, 14, 16, 18])

Comparison operation
You can perform elements wise comparison

# Summarize Numpy provides function for


In [59]:
a.std()

1.4142135623730951